# SPDX-License-Identifier: GPL-2.0
#
# Makefile for Open-Channel SSDs.
#

obj-$(CONFIG_NVM)	:= core.o
obj-m		:= pblk.o ocssdr.o
pblk-y				:= pblk-init.o pblk-core.o pblk-rb.o \
				   pblk-write.o pblk-cache.o pblk-read.o \
				   pblk-gc.o pblk-err-rec.o pblk-recovery.o pblk-map.o \
				   pblk-rl.o pblk-sysfs.o
