#!/bin/bash
# recover
nvme lnvm create -d 1n1,2n1,3n1,4n1,5n1 --lun-begin=0 --lun-end=31 -n pblk_md -t pblk

# recover and resize
#nvme lnvm create -d 1n1,2n1,3n1,4n1,5n1, --lun-begin=0 --lun-end=31 -n pblk_md -t pblk
